[package]
name = "trans-epub"
version = "0.0.3"
edition = "2021"
description = "Translate EPUB with CLI"
repository = "https://github.com/tomiyan/trans-epub"
homepage = "https://github.com/tomiyan/trans-epub"
documentation = "https://github.com/tomiyan/trans-epub"
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.7", features = ["derive", "env"]}
zip = "2.1.3"
reqwest = { version = "0.12.4", features = ["json"] }
quick-xml = "0.32.0"
tokio = { version = "1", features = ["full"]}
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
regex = "1.10.5"
env_logger = "0.11.3"
log = "0.4.21"
futures = "0.3.30"
